### ISSUE TITLE
Aggregate process should check and ignore invalid flow records.

### ISSUE THREAD

**Issue by srikartati** [vmware/go-ipfix#123]
**Describe the bug**

This was raised through an issue in Antrea: https://github.com/vmware-tanzu/antrea/issues/1747

```
W0112 14:28:55.161455       1 aggregate.go:247] This field with name destinationClusterIPv4 should not have been filled with value <nil> in existing record.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6e38ad]

goroutine 21 [running]:
github.com/vmware/go-ipfix/pkg/intermediate.(*AggregationProcess).aggregateRecords(0xc0000a2150, 0x91b820, 0xc002a33230, 0x91b820, 0xc000216870, 0x100, 0x88fe4a, 0x12)
	/go/pkg/mod/github.com/vmware/go-ipfix@v0.4.2/pkg/intermediate/aggregate.go:312 +0x5ad
github.com/vmware/go-ipfix/pkg/intermediate.(*AggregationProcess).addOrUpdateRecordInMap(0xc0000a2150, 0xc000e07d70, 0x91b820, 0xc002a33230, 0x0, 0x0)
	/go/pkg/mod/github.com/vmware/go-ipfix@v0.4.2/pkg/intermediate/aggregate.go:176 +0x2db
github.com/vmware/go-ipfix/pkg/intermediate.(*AggregationProcess).AggregateMsgByFlowKey(0xc0000a2150, 0xc001022dc0, 0x2, 0x2)
	/go/pkg/mod/github.com/vmware/go-ipfix@v0.4.2/pkg/intermediate/aggregate.go:118 +0x130
github.com/vmware/go-ipfix/pkg/intermediate.(*worker).start.func1(0xc0000f3680)
	/go/pkg/mod/github.com/vmware/go-ipfix@v0.4.2/pkg/intermediate/worker.go:35 +0x111
created by github.com/vmware/go-ipfix/pkg/intermediate.(*worker).start
	/go/pkg/mod/github.com/vmware/go-ipfix@v0.4.2/pkg/intermediate/worker.go:26 +0x3f
```

Looks like this one is happening because the associated field values in the decoded flow record are invalid. In this case, one of statElements values seems to be invalid. This has to be fixed in go-ipfix library. One possible solution is to validate every incoming flow record if the decoded values are valid or not before doing the aggregation. Will open an issue in go-ipfix repo.

**To Reproduce**
Pass an invalid record.

**Expected behavior**
Invalid flow records should be ignored by the aggregate process.

**Actual Behavior**
application utilizing the aggregation process library in go-ipfix is crashing.

**Versions**
v0.4.2

**Additional context**

**Comment by srikartati** [comment]
Closing this issue as the fix is merged to release-0.4.0 branch. This will be cherrypicked on to the master branch later.
